basePath: /
definitions:
  admin.CreateYachtRequest:
    properties:
      description:
        example: your favorite yacht
        type: string
      image:
        example: https://images.pexels.com/photos/843633/pexels-photo-843633.jpeg?auto=compress&cs=tinysrgb&w=1200
        type: string
      name:
        example: Maxus
        type: string
      price:
        example: 100
        type: number
      type:
        example: yacht
        type: string
    type: object
  admin.UpdateYachtRequest:
    properties:
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      price:
        type: number
      type:
        type: string
    type: object
  admin.Yacht:
    properties:
      created:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      price:
        type: number
      type:
        type: string
      updated:
        type: string
    type: object
  reservations.Request:
    properties:
      from:
        example: "2022-12-16T21:00:00.511Z"
        type: string
      remarks:
        example: please clean it
        type: string
      to:
        example: "2022-12-17T21:00:00.511Z"
        type: string
      yachtID:
        example: 4
        type: integer
    type: object
  reservations.Reservation:
    properties:
      account_id:
        type: integer
      created:
        type: string
      from:
        type: string
      id:
        type: integer
      remarks:
        type: string
      to:
        type: string
      updated:
        type: string
      yacht_id:
        type: integer
    type: object
  sailing.Account:
    properties:
      created:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        items:
          type: integer
        type: array
      role:
        type: string
      updated:
        type: string
    type: object
  sailing.LoginRequest:
    properties:
      email:
        example: mike@mock.com
        type: string
      password:
        example: P@ssw0rd
        type: string
    type: object
  sailing.RegisterRequest:
    properties:
      email:
        example: mike@mock.com
        type: string
      name:
        example: mike
        type: string
      password:
        example: P@ssw0rd
        type: string
    type: object
  yachts.Yacht:
    properties:
      created:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      price:
        type: number
      type:
        type: string
      updated:
        type: string
    type: object
info:
  contact: {}
  description: some API
  title: API
  version: "1.0"
paths:
  /account/login:
    post:
      consumes:
      - application/json
      description: Login existing user
      parameters:
      - description: body
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/sailing.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sailing.Account'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Login
      tags:
      - account
  /account/logout:
    get:
      consumes:
      - application/json
      description: Logout existing user
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Logout
      tags:
      - account
  /account/register:
    post:
      consumes:
      - application/json
      description: Register new account
      parameters:
      - description: body
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/sailing.RegisterRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sailing.Account'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Register
      tags:
      - account
  /admin/create:
    post:
      consumes:
      - application/json
      description: Create yacht
      parameters:
      - description: body
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/admin.CreateYachtRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.Yacht'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Create
      tags:
      - admin
  /admin/list:
    get:
      consumes:
      - application/json
      description: List yachts
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/admin.Yacht'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Create
      tags:
      - admin
  /admin/remove/{id}:
    delete:
      consumes:
      - application/json
      description: Remove yacht
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Remove
      tags:
      - admin
  /admin/yacht/{id}:
    get:
      consumes:
      - application/json
      description: Find yacht
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.Yacht'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Find
      tags:
      - admin
  /admin/yacht/update:
    patch:
      consumes:
      - application/json
      description: Update yacht
      parameters:
      - description: body
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/admin.UpdateYachtRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.Yacht'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Update
      tags:
      - admin
  /reservations:
    post:
      consumes:
      - application/json
      description: Create reservation
      parameters:
      - description: body
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/reservations.Request'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/reservations.Reservation'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Create
      tags:
      - reservations
  /yachts:
    get:
      consumes:
      - application/json
      description: List yachts
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/yachts.Yacht'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: List
      tags:
      - yachts
  /yachts/{id}:
    get:
      consumes:
      - application/json
      description: Find yacht
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/yachts.Yacht'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Find
      tags:
      - yachts
schemes:
- http
- https
swagger: "2.0"
