version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    ports:
      - 1433:1433